# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.IntegerField(unique=True)),
                ('username_uploader', models.CharField(max_length=100)),
                ('title', models.SlugField(max_length=500)),
                ('news_url', models.URLField()),
                ('score', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('sentimental', models.CharField(max_length=10)),
                ('sent_positive', models.FloatField()),
                ('sent_negative', models.FloatField()),
                ('sent_neutral', models.FloatField()),
            ],
        ),
    ]
