# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160907_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
