# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160909_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.SlugField(max_length=500),
        ),
    ]
